name: test

on:
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - run: yarn install
            - name: Build
              run: yarn build
            - name: Run tests
              run: yarn test
